# Generated by Django 3.0.3 on 2020-02-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('Windows 10', 'Windows 10'), ('Windows 8', 'Windows 8'), ('Linux', 'Linux')], max_length=30, null=True),
        ),
    ]
