# Generated by Django 3.0.3 on 2020-02-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0002_profile_operating_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='operating_system',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=30, null=True),
        ),
    ]
