# Generated by Django 3.0.3 on 2020-02-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0003_auto_20200219_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
