# Generated by Django 3.0.3 on 2020-02-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0004_blogsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
