# Generated by Django 3.0.3 on 2020-02-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0005_blogsettings_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogSettings',
            new_name='Controlpanel',
        ),
    ]
