# Generated by Django 3.0.3 on 2020-02-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0008_auto_20200221_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpanel',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
