# Generated by Django 3.0.3 on 2020-02-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0009_controlpanel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpanel',
            name='logo_width',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
