# Generated by Django 3.0.3 on 2020-02-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0010_controlpanel_logo_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpanel',
            name='logo_width',
            field=models.IntegerField(blank=True, max_length=255),
        ),
    ]
