# Generated by Django 3.0.3 on 2020-02-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0011_auto_20200221_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpanel',
            name='logo_width',
            field=models.IntegerField(blank=True),
        ),
    ]
